package com.cloudsql.lab.problem;
import com.cloudsql.lab.problem.model.*;
import java.util.List;

final class OriginalProblems {
    private OriginalProblems() { }
    static List<ProblemDefinition> all() {
        return List.of(
            p(4, "Ready for the Weekend", "Easy", "Basic Select", "Return id, name, and daily_fee for makerspace tools with at least 2 units in_stock and a daily_fee no greater than 15. Order by daily_fee then id ascending.", "SELECT id, name, daily_fee FROM tools WHERE in_stock >= 2 AND daily_fee <= 15 ORDER BY daily_fee, id"),
            p(5, "Riverside Member Directory", "Easy", "Basic Select", "Prepare a community makerspace mailing list. Return id and name for members whose neighborhood is Riverside, ordered by name ascending.", "SELECT id, name FROM members WHERE neighborhood = 'Riverside' ORDER BY name"),
            p(6, "Tool Budget Bands", "Medium", "Advanced Select", "Return id, name, and budget_band for each tool. Fees below 10 are Budget, 10 through 20 are Standard, and above 20 are Premium. Order by id ascending.", "SELECT id, name, CASE WHEN daily_fee < 10 THEN 'Budget' WHEN daily_fee <= 20 THEN 'Standard' ELSE 'Premium' END AS budget_band FROM tools ORDER BY id"),
            p(7, "Above the Shelf Average", "Medium", "Advanced Select", "Return id, name, and kind for tools whose daily_fee exceeds the average fee for their own kind, including tools with no stock in the average. Order by id ascending.", "SELECT t.id, t.name, t.kind FROM tools t WHERE t.daily_fee > (SELECT AVG(x.daily_fee) FROM tools x WHERE x.kind = t.kind) ORDER BY t.id"),
            p(8, "Shelf Inventory Totals", "Easy", "Aggregation", "For every tool kind, return kind, COUNT(*) as tool_count, and SUM(in_stock) as available_units. Include kinds with no rentals. Order by kind ascending.", "SELECT kind, COUNT(*) AS tool_count, SUM(in_stock) AS available_units FROM tools GROUP BY kind ORDER BY kind"),
            p(9, "Multi-day Borrowers", "Medium", "Aggregation", "Find members with at least 4 total rented days. Return member_id and SUM(days) as rented_days, ordered by rented_days descending then member_id ascending. Each rental contributes its own days.", "SELECT member_id, SUM(days) AS rented_days FROM rentals GROUP BY member_id HAVING SUM(days) >= 4 ORDER BY rented_days DESC, member_id"),
            p(10, "Borrowing Receipts", "Easy", "Basic Join", "Return one receipt per rental: rentals.id as rental_id, members.name as member_name, tools.name as tool_name, and days multiplied by daily_fee as charge. Order by rental_id ascending.", "SELECT r.id AS rental_id, m.name AS member_name, t.name AS tool_name, r.days * t.daily_fee AS charge FROM rentals r JOIN members m ON m.id = r.member_id JOIN tools t ON t.id = r.tool_id ORDER BY r.id"),
            p(11, "Quiet Workshop Venues", "Medium", "Basic Join", "List events with no enrollments. Return events.id and venue ordered by id ascending. An enrollment counts even when attended is 0.", "SELECT e.id, e.venue FROM events e LEFT JOIN enrollments n ON n.event_id = e.id WHERE n.event_id IS NULL ORDER BY e.id"),
            p(12, "Neighborhood Rental Champions", "Hard", "Advanced Join", "For each neighborhood, find members with the greatest total rental charge (days times daily_fee). Include members with no rentals with zero and retain ties. Return neighborhood, member_id, member_name, total_charge ordered by neighborhood then member_id ascending.", "SELECT neighborhood, member_id, member_name, total_charge FROM (SELECT m.neighborhood, m.id AS member_id, m.name AS member_name, COALESCE(SUM(r.days * t.daily_fee), 0) AS total_charge, DENSE_RANK() OVER (PARTITION BY m.neighborhood ORDER BY COALESCE(SUM(r.days * t.daily_fee), 0) DESC) AS position FROM members m LEFT JOIN rentals r ON r.member_id = m.id LEFT JOIN tools t ON t.id = r.tool_id GROUP BY m.neighborhood, m.id, m.name) ranked WHERE position = 1 ORDER BY neighborhood, member_id"),
            p(13, "Workshop and Rental Ledger", "Hard", "Advanced Join", "Return one row per member: id, name, rental_count (number of rentals), and attendance_count (enrollments with attended = 1). Include members with no activity with zeros. Avoid multiplying counts across rentals and enrollments. Order by id ascending.", "SELECT m.id, m.name, COALESCE(r.rental_count, 0) AS rental_count, COALESCE(e.attendance_count, 0) AS attendance_count FROM members m LEFT JOIN (SELECT member_id, COUNT(*) AS rental_count FROM rentals GROUP BY member_id) r ON r.member_id = m.id LEFT JOIN (SELECT member_id, COUNT(*) AS attendance_count FROM enrollments WHERE attended = 1 GROUP BY member_id) e ON e.member_id = m.id ORDER BY m.id"),
            p(14, "Two Ways to Join In", "Medium", "Alternative Queries", "Return distinct member_id values for people who either rented a Printing tool or attended event 2. A member meeting both conditions appears once. Order by member_id ascending. Try a set operation.", "SELECT r.member_id FROM rentals r JOIN tools t ON t.id = r.tool_id WHERE t.kind = 'Printing' UNION SELECT member_id FROM enrollments WHERE event_id = 2 AND attended = 1 ORDER BY member_id"),
            p(15, "Complete Textile Toolkit", "Hard", "Alternative Queries", "Find members who have rented every tool of kind Textile at least once. Return id and name ordered by id ascending. Repeat rentals do not replace a missing tool. Try nested existence checks or set reasoning.", "SELECT m.id, m.name FROM members m WHERE NOT EXISTS (SELECT 1 FROM tools t WHERE t.kind = 'Textile' AND NOT EXISTS (SELECT 1 FROM rentals r WHERE r.member_id = m.id AND r.tool_id = t.id)) ORDER BY m.id")
        );
    }
    private static ProblemDefinition p(long id, String title, String difficulty, String category, String text, String sql) {
        return new ProblemDefinition(id, title.toLowerCase(java.util.Locale.ROOT).replace(' ', '-'), title, difficulty, category, text, "SELECT *\nFROM tools;", sql, "problems/community-lab.sql", List.of(
            table("tools", List.of("id", "name", "kind", "daily_fee", "in_stock"), List.of(List.of(1, "Pocket Loom", "Textile", 8, 4), List.of(2, "Clay Wheel", "Ceramics", 25, 0), List.of(3, "Frame Loom", "Textile", 15, 2))),
            table("members", List.of("id", "name", "neighborhood"), List.of(List.of(1, "Nila", "Riverside"), List.of(2, "Dev", "Hilltop"), List.of(3, "Tara", "Riverside"))),
            table("rentals", List.of("id", "member_id", "tool_id", "days"), List.of(List.of(1, 1, 1, 3), List.of(2, 1, 3, 2), List.of(3, 2, 2, 1))),
            table("events", List.of("id", "venue", "capacity"), List.of(List.of(1, "River Studio", 3), List.of(2, "Hill Workshop", 2), List.of(3, "Town Gallery", 4))),
            table("enrollments", List.of("member_id", "event_id", "attended"), List.of(List.of(1, 1, 1), List.of(2, 1, 0), List.of(3, 1, 1)))));
    }
    private static TablePreview table(String name, List<String> columns, List<List<Object>> rows) {
        return new TablePreview(name, columns.stream().map(c -> new ColumnPreview(c, java.util.Set.of("name", "kind", "neighborhood", "venue").contains(c) ? "VARCHAR" : "INTEGER")).toList(), rows);
    }
}
